kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: docker build
    image: plugins/docker
    settings:
      repo: $DOCKER_REPOSITORY
      target: app
      auto_tag: true
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      registry: $DOCKER_REGISTRY
      insecure: true
